> 오버피팅
- 방정식의 개수가 많고, 미지수가 적기 때문에


> cpu, gpu 모나리자 그리기
- https://knhworld.tistory.com/m/456?category=13182
- cpu/ gpu
> gpu e단순 산술 연산을 할 수 있는 것이 많음.
- cpu: 제어 등을 할 수 있는 복한 컨드롤러




# 최적해 구하기
## 1. 역행렬을 이용해 최적해 구하기
> 2 by 2 행렬
- 역행렬이 존재하므로 a, b를 구할 수 있음.

> 정방행렬이 아닐 때
- 슈도 역행렬로 구할 수 있음.
- 의사역행렬: A + = (A.TA)-1 * A.T

> numpy를 수치 계산용으로 사용하는 이유
- 함수 안에 C로 구현 => 빠름
- 단일 데이터 type


In [1]:
import numpy as np
import numpy.linalg as lin

## 1.1 (2,2)역행렬 구하기

#### 행렬의 2열은 항상 1 -> bias값이기 때문에

In [4]:
a = np.array([[1,1],[2,1]])
a.shape

(2, 2)

In [5]:
a_ = lin.inv(a)
a_

array([[-1.,  1.],
       [ 2., -1.]])

In [7]:
y = np.array([2,4])


### 1.1.1 산술 곱

In [8]:
# W 를 곱하기 
w = a_ * y
w

array([[-2.,  4.],
       [ 4., -4.]])

### 1.1.2. 행렬곱

In [11]:
w = np.dot(a_, y)
w

array([2., 0.])

In [12]:
w = np.matmul(a_, y)
w

array([2., 0.])

### 1.1.3. 행렬의 기본: column 방향

In [15]:
# 행렬이 아닌 벡터
y = np.array([2,4])
y.shape

(2,)

In [18]:
# row 방향 행렬
y_= np.array([[2,4]])
y_.shape

(1, 2)

In [22]:
# column 방향 행렬
y_.T.shape
y_.reshape(2,1).shape

(2, 1)

In [20]:
# column 방향 행렬
y_2 = np.array([[2],[4]])
y_2.shape

(2, 1)

In [24]:
w = np.matmul(a_, y_2)
w.shape

# 2차원 행렬에 주의

(2, 1)

In [25]:
w

array([[2.],
       [0.]])

# 2. (2,3) 역행렬 구하기

> 점이 3개가 있는 경우
- 점 3개를 선형으로 표현할 수가 없음.
- 점 2개 / 점2개를 조합하는 모델을 만들어야 함.
- 우리가 원하는 것은 -무한대 ~ 무한대를 표현하는 직선의 방정식을 표현하기 위해
- 

In [26]:
a = np.array([[1,1],[2,1],[3,1]])
a_ = lin.inv(a)

# 정방행렬이 아니기 때문에 역행렬 구할 수 없음.

LinAlgError: Last 2 dimensions of the array must be square

## 2.1. 슈도 역행렬 구하기(pseudo inverse)

In [27]:
a_ = lin.pinv(a)
a_

array([[-5.00000000e-01, -3.19189120e-16,  5.00000000e-01],
       [ 1.33333333e+00,  3.33333333e-01, -6.66666667e-01]])

In [28]:
y = np.array([2,4,6]).reshape(3,1)
w = np.matmul(a_, y)
w

array([[ 2.0000000e+00],
       [-8.8817842e-16]])

## 2.2. 예측값 구하기

In [34]:
x = 1
y = w[0][0]* x + w[1][0]
y

1.9999999999999991

## 2.3. 해석
- 내가 찾은 직선으로는 정확하게 데이터(x, y)를 표현할 수 없음.
- 오차가 있을수밖에 없음.

## 2.4. 데이터가 많을 경우 E를 계산하기 위해서는 행렬로 만들어야 함.

In [42]:
y = w[0][0]* np.array([-1,0,1,2]) + w[1][0]
y

array([-2.0000000e+00, -8.8817842e-16,  2.0000000e+00,  4.0000000e+00])

In [43]:
# bias값이 있어야 하기 때문에 항상 1을 넣어야 함.
x_ = np.array([[-1,1],[0,1],[1,1],[2,1]])
np.matmul(x_, w)

array([[-2.0000000e+00],
       [-8.8817842e-16],
       [ 2.0000000e+00],
       [ 4.0000000e+00]])